//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

package lt.viko.eif.nychyporuk.client.modelgen;

import jakarta.xml.bind.annotation.XmlTransient;

/**
 * An abstract base class for entities that are used in XML binding processes.
 * Provides a common ID property that can be inherited by subclasses.
 * The ID property is marked with @XmlTransient to indicate that it should not
 * be serialized into XML or unserialized from XML.
 */
public abstract class BaseEntity {
    private int id;

    /**
     * Default constructor.
     */
    public BaseEntity() {
    }

    /**
     * Constructs a new BaseEntity with a specified ID.
     *
     * @param id the ID of the entity.
     */
    public BaseEntity(int id) {
        this.id = id;
    }

    /**
     * Returns the ID of this entity.
     *
     * @return the ID of the entity.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the ID of this entity.
     *
     * @param id the new ID of the entity.
     */
    @XmlTransient
    public void setId(int id) {
        this.id = id;
    }
}
