//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package lt.viko.eif.nychyporuk.client.modelgen;

import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for guideType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="guideType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="experience" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlType(propOrder = {"firstName", "lastName", "experience"})
public class Guide {

    protected String firstName;
    protected String lastName;
    protected byte experience;


    /**
     * Default constructor.
     */
    public Guide() {
    }

    /**
     * Constructs a new Guide with specified first name, last name, and experience.
     *
     * @param firstName The first name of the guide.
     * @param lastName  The last name of the guide.
     * @param experience The number of years the guide has experience.
     */
    public Guide(String firstName, String lastName, byte experience) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.experience = experience;
    }

    /**
     * Writes object's data into string
     *
     * @return String with object's data
     */
    @Override
    public String toString() {
        return String.format("\tGuide: \n" +
                "\t\tFirstName: %s \n" +
                "\t\tLastName: %s \n" +
                "\t\tExperience: %s \n", this.firstName, this.lastName, this.experience);
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the experience property.
     * 
     */
    public byte getExperience() {
        return experience;
    }

    /**
     * Sets the value of the experience property.
     * 
     */
    public void setExperience(byte value) {
        this.experience = value;
    }

}
