//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package lt.viko.eif.nychyporuk.client.modelgen;

import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sightType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="sightType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="The Gediminas' Tower"/>
 *               <enumeration value="Museum of Occupations and Freedom Fights"/>
 *               <enumeration value="Riga Dome Cathedral"/>
 *               <enumeration value="Freedom Monument"/>
 *               <enumeration value="Tallinn Old Town"/>
 *               <enumeration value="Tallinn TV Tower"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="duration">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               <enumeration value="3"/>
 *               <enumeration value="2"/>
 *               <enumeration value="1"/>
 *               <enumeration value="5"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlType(propOrder = {"name", "duration"})
public class Sight {

    protected String name;
    protected byte duration;

    /**
     * Default constructor.
     */
    public Sight() {
    }

    /**
     * Constructs a new Sight with specified name and duration of visit.
     *
     * @param name The name of the sightseeing location.
     * @param duration The duration of the visit in minutes.
     */
    public Sight(String name, byte duration) {
        this.name = name;
        this.duration = duration;
    }

    /**
     * Writes object's data into string
     *
     * @return String with object's data
     */
    @Override
    public String toString() {
        return String.format("\t\tSight: \n" +
                "\t\t\tName: %s \n" +
                "\t\t\tDuration: %s \n", this.name, this.duration);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public byte getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(byte value) {
        this.duration = value;
    }

}
