//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package lt.viko.eif.nychyporuk.client.modelgen;

import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tourType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="tourType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="duration" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         <element name="visits" type="{}visitsType"/>
 *         <element name="guide" type="{}guideType"/>
 *         <element name="price" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlRootElement(name = "tour")
@XmlType(propOrder = {"name", "duration", "visits", "guide", "price"})
public class Tour {

    protected String name;
    protected byte duration;
    private List<Visit> visits = new ArrayList<>();
    protected Guide guide;
    protected short price;

    /**
     * Default constructor.
     */
    public Tour() {
    }

    /**
     * Constructs a new Tour with specified name, duration, guide, and price.
     *
     * @param name     The name of the tour.
     * @param duration The duration of the tour in minutes.
     * @param guide    The guide leading the tour.
     * @param price    The price of the tour.
     */
    public Tour(String name, byte duration, Guide guide, short price) {
        this.name = name;
        this.duration = duration;
        this.guide = guide;
        this.price = price;
    }

    /**
     * Writes object's data into string
     *
     * @return String with object's data
     */
    @Override
    public String toString() {
        return String.format("Tour: \n" +
                "\tName: %s \n" +
                "\tVisits: %s" +
                "\tDuration: %s \n" +
                "%s" +
                "\tPrice: %s \n", this.name, constructVisitsList(), this.duration, this.guide, this.price);
    }

    /**
     * Concatenates visits' string representations
     *
     * @return String with visits' data
     */
    public String constructVisitsList() {
        String result = "\n";
        for (Visit v : this.visits) {
            result += v;
        }

        return result;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public byte getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(byte value) {
        this.duration = value;
    }

    /**
     * Gets the value of the visits list property.
     *
     * @return
     *     possible object is list of
     *     {@link Visit }
     *
     */
    public List<Visit> getVisits() {
        return visits;
    }

    /**
     * Sets the value of the visits list property.
     *
     * @param value
     *     allowed object is list of
     *     {@link Visit }
     *
     */
    @XmlElementWrapper(name = "visits")
    @XmlElement(name = "visit")
    public void setVisits(List<Visit> value) {
        this.visits = value;
    }

    /**
     * Gets the value of the guide property.
     * 
     * @return
     *     possible object is
     *     {@link Guide }
     *     
     */
    public Guide getGuide() {
        return guide;
    }

    /**
     * Sets the value of the guide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Guide }
     *     
     */
    public void setGuide(Guide value) {
        this.guide = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public short getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(short value) {
        this.price = value;
    }

}
