//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package lt.viko.eif.nychyporuk.client.modelgen;

import jakarta.xml.bind.annotation.*;

import java.util.List;


/**
 * <p>Java class for visitType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="visitType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="country">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="Lithuania"/>
 *               <enumeration value="Latvia"/>
 *               <enumeration value="Estonia"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="city">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="Vilnius"/>
 *               <enumeration value="Riga"/>
 *               <enumeration value="Tallinn"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="duration" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         <element name="hotel" type="{}hotelType"/>
 *         <element name="sights" type="{}sightsType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlType(propOrder = {"country", "city", "duration", "hotel", "sights"})
public class Visit {

    protected String country;
    protected String city;
    protected byte duration;
    protected Hotel hotel;
    protected List<Sight> sights;


    /**
     * Default constructor.
     */
    public Visit() {
    }

    /**
     * Constructs a Visit with specified details.
     *
     * @param country The country of the visit.
     * @param city The city of the visit.
     * @param duration The duration of the visit in days.
     * @param hotel The hotel for the visit.
     */
    public Visit(String country, String city, byte duration, Hotel hotel) {
        this.country = country;
        this.city = city;
        this.duration = duration;
        this.hotel = hotel;
    }

    /**
     * Writes object's data into string
     *
     * @return String with object's data
     */
    @Override
    public String toString() {
        return String.format("\tVisit: \n" +
                "\t\tCountry: %s \n" +
                "\t\tCity: %s \n" +
                "\t\tDuration: %s \n" +
                "%s" +
                "\t\tSights: %s", this.country, this.city, this.duration, this.hotel, constructSightsList());
    }

    /**
     * Concatenates sights' string representations
     *
     * @return String with sights' data
     */
    public String constructSightsList() {
        String result = "\n";
        for (Sight s : this.sights) {
            result += s;
        }

        return result;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public byte getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(byte value) {
        this.duration = value;
    }

    /**
     * Gets the value of the hotel property.
     * 
     * @return
     *     possible object is
     *     {@link Hotel }
     *     
     */
    public Hotel getHotel() {
        return hotel;
    }

    /**
     * Sets the value of the hotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hotel }
     *     
     */
    public void setHotel(Hotel value) {
        this.hotel = value;
    }

    /**
     * Gets the value of the sights list property.
     *
     * @return
     *     possible object is list of
     *     {@link Sight }
     *
     */
    public List<Sight> getSights() {
        return sights;
    }

    /**
     * Sets the value of the sights list property.
     *
     * @param value
     *     allowed object is list of
     *     {@link Sight }
     *
     */
    @XmlElementWrapper(name = "sights")
    @XmlElement(name = "sight")
    public void setSights(List<Sight> value) {
        this.sights = value;
    }

}
